import emptyUser from "../images/emptyUser.png";

const API_BASE_URL_DEVELOPMENT = 'https://localhost:7129/api'
const API_BASE_URL_PRODUCTION = 'https://azure:7180/api'


const ENDPOINTS = (messageID=null, contactID=null) => ({
    REGISTER_USER: 'users/register',
    LOGIN_USER: 'users/login',
    AUTHENTICATE_USER: 'users/token',
    
    GET_ALL_CONTACTS: 'contacts',
    GET_CONTACT_BY_ID: `contacts/${contactID}`,
    CREATE_CONTACT: `contacts`,

    GET_ALL_MESSAGES_BY_CONTACTS: `contacts/${contactID}/messages`,
    GET_MESSAGE_BY_ID_BY_CONTACT: `contacts/${contactID}/messages/${messageID}`,
    CREATE_MESSAGE_BY_CONTACT: `contacts/${contactID}/messages`,

    TRANSFER_MESSAGE: `transfer`,
    INVITE_MEMBER: `invite`,

    CHAT_CONNECTION: 'chat_connect',
    CONTACT_CONNECTION: 'contact_connect',
})

const development = (contactID=null, messageID=null, contactServer=null) => ({
    API_URL_REGISTER_USER: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS().REGISTER_USER}`,
    API_URL_LOGIN_USER: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS().LOGIN_USER}`,
    API_URL_AUTHENTICATE_USER: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS().AUTHENTICATE_USER}`,

    API_URL_GET_ALL_CONTACTS: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS().GET_ALL_CONTACTS}`,
    API_URL_GET_CONTACT_BY_ID: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS(null,contactID).GET_CONTACT_BY_ID}`,
    API_URL_CREATE_CONTACT: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS().CREATE_CONTACT}`,

    API_URL_GET_ALL_MESSAGES_BY_CONTACT: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS(null,contactID).GET_ALL_MESSAGES_BY_CONTACTS}`,
    API_URL_GET_MESSAGE_BY_ID_BY_CONTACT: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS(messageID, contactID).GET_MESSAGE_BY_ID_BY_CONTACT}`,
    API_URL_CREATE_MESSAGE_BY_CONTACT: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS(null,contactID).CREATE_MESSAGE_BY_CONTACT}`,

    API_URL_TRANSFER_MESSAGE: `https://${contactServer}/api/${ENDPOINTS().TRANSFER_MESSAGE}`,
    API_URL_INVITE_MEMBER: `https://${contactServer}/api/${ENDPOINTS().INVITE_MEMBER}`,

    API_URL_CHAT_CONNECTION: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS().CHAT_CONNECTION}`,
    API_URL_CONTACT_CONNECTION: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS().CONTACT_CONNECTION}`,
})

const production = (messageID=null, contactID=null, contactServer=null) => ({
    API_URL_REGISTER_USER: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS().REGISTER_USER}`,
    API_URL_LOGIN_USER: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS().LOGIN_USER}`,
    API_URL_AUTHENTICATE_USER: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS().AUTHENTICATE_USER}`,

    API_URL_GET_ALL_CONTACTS: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS().GET_ALL_CONTACTS}`,
    API_URL_GET_CONTACT_BY_ID: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS(null,contactID).GET_CONTACT_BY_ID}`,
    API_URL_CREATE_CONTACT: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS().CREATE_CONTACT}`,

    API_URL_GET_ALL_MESSAGES_BY_CONTACT: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS(null,contactID).GET_ALL_MESSAGES_BY_CONTACTS}`,
    API_URL_GET_MESSAGE_BY_ID_BY_CONTACT: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS(messageID, contactID).GET_MESSAGE_BY_ID_BY_CONTACT}`,
    API_URL_CREATE_MESSAGE_BY_CONTACT: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS(null,contactID).CREATE_MESSAGE_BY_CONTACT}`,

    API_URL_TRANSFER_MESSAGE: `${contactServer}/${ENDPOINTS().TRANSFER_MESSAGE}`,
    API_URL_INVITE_MEMBER: `${contactServer}/${ENDPOINTS().INVITE_MEMBER}`,

    API_URL_CHAT_CONNECTION: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS().CHAT_CONNECTION}`,
    API_URL_CONTACT_CONNECTION: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS().CONTACT_CONNECTION}`,
})

const constants = process.env.NODE_ENV === 'development' ? development : production;

export const nullUser = { username: null, displayName: null, password: null, profilePic: emptyUser};


export const actionTypes = {
    SET_USER: "SET_USER",
    RENDER: "RENDER",
    SET_CHAT_CONNECTION: "SET_CHAT_CONNECTION",
    SET_CONTACT_CONNECTION: "SET_CONTACT_CONNECTION",
  };

export default constants